services:
  mongo:
    image: mongo:7
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: nosql_logs
    volumes:
      - mongo_data:/data/db

  ingest:
    build:
      context: ./ingest
      dockerfile: Dockerfile
    container_name: logdb_ingest
    environment:
      MONGO_URI: "mongodb://mongo:27017"
      MONGO_DB: "nosql_logs"
      MONGO_COLLECTION: "logs"
      LOG_DIR: "/input-logfiles"
    depends_on:
      - mongo
    volumes:
      - ./input-logfiles:/input-logfiles:ro
    restart: "no"
    command: >
      bash -c '
        ts() { date "+%Y-%m-%d %H:%M:%S.%3N"; }
        echo "$(ts) | Ingest step deployment: START."
        python execute.py
        echo "$(ts) | Ingest step deployment: END."
      '

  seed:
    build:
      context: ./seed
      dockerfile: Dockerfile
    container_name: logdb_seed
    environment:
      MONGO_URI: "mongodb://mongo:27017"
      MONGO_DB: "nosql_logs"
      N_ADMINS: "500"
      EXTRA_VOTE_FRAC: "0.20"
      ADMIN_CAP: "1000"
      MODE: "fail"
    depends_on:
      - ingest
    restart: "no"
    command: >
      bash -c '
        ts() { date "+%Y-%m-%d %H:%M:%S.%3N"; }
        echo "$(ts) | Seed step deployment: START."
        python admins.py
        python upvotes.py
        echo "$(ts) | Seed step deployment: END."
      '

  api:
    build: ./api
    container_name: logdb_api
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: "mongodb://mongo:27017"
      MONGO_DB: "nosql_logs"
    depends_on:
      - mongo
    restart: "no"

volumes:
  mongo_data:
